USE menu_maker;
DROP TABLE IF EXISTS food;
CREATE TABLE food (
	id int NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	type VARCHAR(30),
	last_used DATE,
	ingredients INTEGER,
	bbq BOOLEAN,
	theme VARCHAR(30),
    PRIMARY KEY (id)
);

-- Seed some starting data to test. 
INSERT INTO food (name, type, bbq, theme)
VALUES 
	('Hamburgers', 'main', true, 'red meat'),
    ('Spaghetti', 'meal', false, 'pasta'),
    ('Orzo Salad', 'side', false, 'salad'),
    ('Maple Glazed Salmon', 'main', false, 'fish'),
    ('Caesar Salad', 'side', false, 'salad'),
    ('Porto Rico Potatoes', 'starch', false, 'potato'),
    ('Green Beans', 'veg', false, 'salad'),
    ('Carrot Coins', 'veg', false, 'salad'),
    ('Corn on the Cob', 'veg', true, 'salad'),
    ('Sugar Snap Peas', 'veg', false, 'salad'), 
    ('Peppers', 'veg', false, 'salad'),
    ('Indian Meal Kit', 'meal', false, 'chicken'), 
    ('Chicken Thighs', 'main', true, 'chicken'), 
    ('Home Made Pizza', 'meal', false, 'pasta'),
    ('Hot Dogs', 'main', true, 'red meat'),
    ('Roast Potatoes', 'starch', false, 'potato'),
    ('Fries', 'starch', false, 'potato'),
    ('Tater Tots', 'starch', false, 'potato'),
    ('Rice', 'starch', false, 'pasta'),
    ('Pork Kabobs', 'main', true, 'red meat'),
    ('Jambalaya', 'meal', false, 'pasta'),
    ('Tubes and Cubes', 'meal', false, 'chicken'),
    ('Pad Grah Pow', 'meal', false, 'asian'),
    ('Pad Thai', 'meal', false, 'asian'),
    ('Nachos', 'meal', false, 'fast'),
    ('Fast Chili', 'meal', false, 'soup'),
    ('Slow-cooker Chili', 'meal', FALSE, 'soup'),
    ('Lazy Lasagna', 'meal', false, 'pasta'),
    ('Chicken Burger', 'main', false, 'chicken'),
    ('Steak', 'main', true, 'red meat'),
    ('Ribs', 'main', true, 'red meat'),
    ('Bacon Wrapped Scallops', 'main', false, 'fish'), 
    ('Pick Plate', 'meal', false, 'fast'), 
    ('Fajias', 'meal', false, 'mexican'),
    ('Stir Fry', 'meal', false, 'fast'),
    ('Tim''s Fish', 'main', FALSE, 'fish'),
    ('Tacos', 'meal', FALSE, 'mexican'),
    ('Penne for Your Thoughts', 'meal', FALSE, 'pasta'),
    ('Worth Every Penne', 'meal', FALSE, 'pasta'),
    ('Marla''s Maple Pork', 'main', FALSE, 'pork'),
    ('Stew', 'meal', FALSE, 'red meat'),
    ('Grocery Cart Chicken Chili', 'meal', FALSE, 'chicken'),
    ('Fajitas', 'meal', FALSE, 'mexican'),
    ('BLTs', 'main', FALSE, 'fast'),
    ('Grilled Cheese Sandwiches', 'main', FALSE, 'fast'),
    ('Butter Chicken Naan-Bread Pizza', 'meal', FALSE, 'chicken'),
    ('Greek Wraps', 'main', FALSE, 'chicken'),
    ('Lemon Chicken Orzo Soup', 'meal', FALSE, 'soup'),
    ('Butternut Squash Soup', 'meal', FALSE, 'soup'),
    ('Quinoa and Sweet Potato Skillet', 'meal', FALSE, 'mexican'),
    ('Roasted Asian Salmon', 'main', FALSE, 'fish'),
    ('Grilled Chicken Souvlaki', 'main', TRUE, 'chicken'),
    ('Chicken Penne Florentine', 'meal', FALSE, 'pasta'),
    ('Maple Curry Chicken', 'main', FALSE, 'chicken'),
    ('Chicken Enchilada Casserole', 'meal', FALSE, 'chicken'),
    ('Asian Chicken Lettus Wraps', 'meal', FALSE, 'asian'),
    ('Beef Bowlrito', 'meal', FALSE, 'mexican'),
    ('Asian Grilled Pork Kabobs', 'main', TRUE, 'asian'),
    ('Curried Coconut Rice', 'side', FALSE, 'asian'),
    ('Roasted Fall Vegetables', 'side', FALSE, 'salad'),
    ('Grilled Corn Salsa', 'side', TRUE, 'salad'),
    ('Gringo Star', 'meal', FALSE, 'pasta'), 
    ('Slow Cooker Roast Chicken', 'main', FALSE, 'chicken'), 
    ('Sticky Chicky', 'main', FALSE, 'chicken'),
    ('A Wok in the Pork', 'meal', FALSE, 'pork'),
    ('Mexican Lasagna', 'meal', FALSE, 'pasta'),
    ('The Rice is Right', 'meal', FALSE, 'asian')
;